---
apiVersion: v2
name: quasarbroker
version: 0.0.1
description: simple quasarbroker installation
type: application

dependencies:
  - name: app-template
    alias: quasarbroker
    version: ~4
    repository: https://bjw-s-labs.github.io/helm-charts/
